dependencies = [
    "matplotlib==3.8.3",
    "numpy==1.26.4",
    "pandas==2.2.1",
    "pillow==10.2.0",
    "scikit-learn==1.4.1",
    "scipy==1.13.1",
    "torch==2.2.1",
    "torchvision==0.17.1",
    "tqdm==4.66.2",
    "wandb==0.17.2",
]

[tool.ruff]
line-length = 100

exclude = ["excluded_file.py"]
lint.select = [
    "E",  # pycodestyle errors (settings from FastAPI, thanks, @tiangolo!)
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]
lint.ignore = [
    "E501",  # line too long
    "C901",  # too complex
]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint.isort]
order-by-type = true
relative-imports-order = "closest-to-furthest"
extra-standard-library = ["typing"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-first-party = []